/**
 * Values several specs type into the application, declared once so a change -
 * or a typo - happens in one place (`RulesForWritingTests.md` §9).
 *
 * Credentials never live here: they come from `.env` through
 * `specs/support/env.ts`. Data a test creates and must find again (titles,
 * message bodies) is generated by `src/helpers/data/`, not declared here.
 */

/** A real place for the post-form specs to describe; any non-empty strings would do. */
export const LOCATION = {
  morskieOko: {
    locationCountry: 'Poland',
    locationCity: 'Malopolska',
    lastCountry: 'Poland',
    lastRegion: 'Krakow',
  },
} as const;

/** Values for the post form's free-text `currency` field. */
export const CURRENCY = {
  pln: 'PLN',
  eur: 'EUR',
} as const;

/**
 * An id no row will ever have - the largest `int`, which an `IDENTITY(1, 1)`
 * column does not reach in this application's lifetime. For requests about
 * something that does not exist.
 */
export const MISSING_ID = 2_147_483_647;

/**
 * `API/Data/UserSeedData.json`, loaded by `Seed.SeedUsers` - lower-cased, as the
 * database stores usernames. No spec signs in as them; they are what a real
 * visitor sees, so the suite only reads their data.
 */
export const SEED = {
  members: ['lisa', 'jessie', 'celina', 'wilda', 'madeleine', 'bob', 'oneill', 'reid', 'durham', 'smith'],
} as const;

/** Schema facts the suite relies on, as `API/Data/Migrations` defines them. */
export const SCHEMA = {
  /** Every migration in `API/Data/Migrations`, oldest first - add one here whenever the application adds one. */
  migrations: ['20250302123454_InitialCreate'],
  /** Deleting a post deletes its likes with it - `[ID: 75]` depends on it. */
  likesToPostsForeignKey: { name: 'FK_Likes_Posts_PostId', fromTable: 'Likes', toTable: 'Posts', onDelete: 'CASCADE' },
} as const;
